
package alquiler.trajes.form.utility;

import alquiler.trajes.constant.ApplicationConstants;
import alquiler.trajes.constant.PropertyConstant;
import alquiler.trajes.util.PropertySystemUtil;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class UtilityForm extends javax.swing.JInternalFrame {

    private static final Logger logger = Logger.getLogger(UtilityForm.class.getName());
    public UtilityForm() {
        initComponents();
        this.setClosable(true);
        this.setTitle(ApplicationConstants.TITLE_UTILITY_FORM);
        init();
    }
    
    private void init () {
        
        disableForm();
        
        try {
            Long plusDays = 
                    Long.valueOf(PropertySystemUtil.get(PropertyConstant.PLUS_DAYS_TO_EVENTS_IN_MAIN_FORM));            
            txtPlusDaysToEventsInMainForm.setText(String.valueOf(plusDays));
            
            
            Integer minutesToRequestNewSession = 
                    Integer.valueOf(PropertySystemUtil.get(PropertyConstant.MINUTES_TO_REQUEST_NEW_SESSION));
            txtMinutesToRequestNewSession.setText(String.valueOf(minutesToRequestNewSession));
            
            Boolean calculateReturnDate = 
                    Boolean.valueOf(PropertySystemUtil.get(PropertyConstant.CALCULATE_RETURN_DATE));
            checkCalculateReturnDate.setSelected(calculateReturnDate);           
            
            
         } catch(IOException e){
            logger.log(Level.SEVERE,e.getMessage(),e);           
            JOptionPane.showMessageDialog(this, e, ApplicationConstants.MESSAGE_UNEXPECTED_ERROR,
                    JOptionPane.ERROR_MESSAGE);
        } 
        
    }
    
    private void disableForm () {
        txtMinutesToRequestNewSession.setEnabled(false);
        txtPlusDaysToEventsInMainForm.setEnabled(false);
        checkCalculateReturnDate.setEnabled(false);
        jbtnSave.setEnabled(false);
    }
    
    private void enableForm () {
        txtMinutesToRequestNewSession.setEnabled(true);
        txtPlusDaysToEventsInMainForm.setEnabled(true);
        checkCalculateReturnDate.setEnabled(true);
        jbtnSave.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMinutesToRequestNewSession = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPlusDaysToEventsInMainForm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        checkCalculateReturnDate = new javax.swing.JCheckBox();
        jbtnEdit = new javax.swing.JButton();
        jbtnSave = new javax.swing.JButton();

        jLabel1.setText("Tiempo para volver a solicitar contraseña (minutos):");

        jLabel2.setText("Número de días posteriores para mostrar eventos en la ventana principal:");

        jLabel3.setText("¿Calcular fecha de devolución en la ventana de eventos?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMinutesToRequestNewSession, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(txtPlusDaysToEventsInMainForm)
                    .addComponent(checkCalculateReturnDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMinutesToRequestNewSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtPlusDaysToEventsInMainForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkCalculateReturnDate)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("General", jPanel2);

        jbtnEdit.setText("Editar");
        jbtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditActionPerformed(evt);
            }
        });

        jbtnSave.setText("Guardar");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnSave)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnEdit)
                    .addComponent(jbtnSave))
                .addGap(179, 179, 179))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
       try {
            
           Long plusDays = Long.valueOf(txtPlusDaysToEventsInMainForm.getText().trim());
           Integer minutesToRequestNewSession = Integer.valueOf(txtMinutesToRequestNewSession.getText().trim());
           Boolean calculateReturnDate = checkCalculateReturnDate.isSelected();
           
           PropertySystemUtil
                   .save(PropertyConstant.MINUTES_TO_REQUEST_NEW_SESSION.getKey(),String.valueOf(minutesToRequestNewSession));
           PropertySystemUtil
                   .save(PropertyConstant.PLUS_DAYS_TO_EVENTS_IN_MAIN_FORM.getKey(),String.valueOf(plusDays));
           PropertySystemUtil
                   .save(PropertyConstant.CALCULATE_RETURN_DATE.getKey(),String.valueOf(calculateReturnDate)); 
           
           this.disableForm();
           
       } catch (NumberFormatException numberFormatException) {
           JOptionPane.showMessageDialog(
                   this, ApplicationConstants.MESSAGE_TITLE_ERROR,
                   ApplicationConstants.MESSAGE_NUMBER_FORMAT_ERROR,
                   JOptionPane.ERROR_MESSAGE);
       } catch (IOException ioe) {
           JOptionPane.showMessageDialog(
                   this, ApplicationConstants.MESSAGE_TITLE_ERROR,
                   ioe.getMessage(),
                   JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void jbtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditActionPerformed
        enableForm();
    }//GEN-LAST:event_jbtnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkCalculateReturnDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtnEdit;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JTextField txtMinutesToRequestNewSession;
    private javax.swing.JTextField txtPlusDaysToEventsInMainForm;
    // End of variables declaration//GEN-END:variables
}
